name: 'de_challenge_ar'
version: '1.0.0'
config-version: 2

profile: 'portfolio_etl_argentina'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  de_challenge_ar:
    staging:
      +materialized: view
    marts:
      +materialized: table